# 
name: LXP
version: "1.1.2"
slug: lxp
description: LXP
url: "https://https://github.com/davewinwood/lxp/tree/main/example/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello LXP world..."
schema:
  message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
