# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.1.0"
slug: example
description: Example add-on
url: "https://https://github.com/davewinwood/lxp/blob/main/example/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello LXP world..."
schema:
  message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
